version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:80"
  selenium:
    image: "selenium/standalone-chrome:4.2.2-20220609"
    ports:
      - "4444:4444"
    depends_on:
        - api
    environment:
        - SE_NODE_MAX_SESSIONS=100
        - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: "2gb"