apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -v
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -v
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: selenium
    spec:
      containers:
        - env:
            - name: SE_NODE_MAX_SESSIONS
              value: "100"
            - name: SE_NODE_OVERRIDE_MAX_SESSIONS
              value: "true"
          image: selenium/standalone-chrome:4.2.2-20220609
          name: selenium
          ports:
            - containerPort: 4444
          resources: {}
      restartPolicy: Always
status: {}
