apiVersion: apps/v1
kind: Deployment
metadata:
  name: bball-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bball-api
  template:
    metadata:
      labels:
        app: bball-api
    spec:
      restartPolicy: Always
      containers: 
      - name: api
        image: us-central1-docker.pkg.dev/basketball-api-340719/api/api:latest
        ports:
        - containerPort: 5000   

      - name: selenium-event-bus
        image: selenium/event-bus:4.2.2-20220609
        container_name: selenium-event-bus
        ports:
          - "4442:4442"
          - "4443:4443"
          - "5557:5557"

      - name: selenium-sessions
        image: selenium/sessions:4.2.2-20220609
        container_name: selenium-sessions
        ports:
          - "5556:5556"
        depends_on:
          - selenium-event-bus
        environment:
          - SE_EVENT_BUS_HOST=selenium-event-bus
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

      - name: selenium-session-queue
        image: selenium/session-queue:4.2.2-20220609
        container_name: selenium-session-queue
        ports:
          - "5559:5559"
        depends_on:
          - selenium-event-bus
        environment:
          - SE_EVENT_BUS_HOST=selenium-event-bus
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

      - name: selenium-distributor
        image: selenium/distributor:4.2.2-20220609
        container_name: selenium-distributor
        ports:
          - "5553:5553"
        depends_on:
          - selenium-event-bus
          - selenium-sessions
          - selenium-session-queue
        environment:
          - SE_EVENT_BUS_HOST=selenium-event-bus
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
          - SE_SESSIONS_MAP_HOST=selenium-sessions
          - SE_SESSIONS_MAP_PORT=5556
          - SE_SESSION_QUEUE_HOST=selenium-session-queue
          - SE_SESSION_QUEUE_PORT=5559

      - name: selenium-router
        image: selenium/router:4.2.2-20220609
        container_name: selenium-router
        ports:
          - "4444:4444"
        depends_on:
          - selenium-distributor
          - selenium-sessions
          - selenium-session-queue
        environment:
          - SE_DISTRIBUTOR_HOST=selenium-distributor
          - SE_DISTRIBUTOR_PORT=5553
          - SE_SESSIONS_MAP_HOST=selenium-sessions
          - SE_SESSIONS_MAP_PORT=5556
          - SE_SESSION_QUEUE_HOST=selenium-session-queue
          - SE_SESSION_QUEUE_PORT=5559

      - name: chrome
        image: selenium/node-chrome:4.2.2-20220609
        shm_size: 2gb
        depends_on:
          - selenium-event-bus
        environment:
          - SE_EVENT_BUS_HOST=selenium-event-bus
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

      - name: edge
        image: selenium/node-edge:4.2.2-20220609
        shm_size: 2gb
        depends_on:
          - selenium-event-bus
        environment:
          - SE_EVENT_BUS_HOST=selenium-event-bus
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

      - name: firefox
        image: selenium/node-firefox:4.2.2-20220609
        shm_size: 2gb
        depends_on:
          - selenium-event-bus
        environment:
          - SE_EVENT_BUS_HOST=selenium-event-bus
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443