apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-edge
  labels:
    app: selenium-node-edge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-edge
  template:
    metadata:
      labels:
        app: selenium-node-edge
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-edge
        image: selenium/node-edge:4.0
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: SE_EVENT_BUS_HOST
            value: "selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
          - name: SE_NODE_MAX_SESSIONS
            value: "10"
          - name: SE_NODE_OVERRIDE_MAX_SESSIONS
            value: "true"
        resources:
          limits:
            memory: "1100Mi"
            cpu: ".5"